//
//  CalculatorWorker.swift
//  MVVM_VS_VIP
//
//  Created by Papon Supamongkonchai on 7/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CalculatorWorker
{
    func calculatePlusWork()
    {
        
    }
    
    func calculateMinusWork()
    {
        
    }
    
    func calculateMultiplyWork()
    {
        
    }
    
    func calculateDivideWork()
    {
        
    }
}
